name: Docker Image CI

on:
  push:
    branches: [ main ]
  #pull_request:
  # branches: [ main ]
    
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: saurtiwa3/hello-world
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hello-world:$(date +%s)
